# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseorg',
            options={'verbose_name': '\u8bfe\u7a0b\u673a\u6784', 'verbose_name_plural': '\u8bfe\u7a0b\u673a\u6784'},
        ),
    ]
