# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180319_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='user',
            field=models.IntegerField(default=0, verbose_name='\u63a5\u6536\u7528\u6237'),
        ),
    ]
