# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180319_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_click',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u70b9\u51fb'),
        ),
    ]
